# Generated by Django 6.0.6 on 2026-07-03 05:01

import app.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso (+)'), ('EGRESO', 'Egreso (-)')], max_length=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(choices=[('Ventas', 'Ventas'), ('Servicios', 'Servicios'), ('Anticipos', 'Anticipos de clientes'), ('Arriendo', 'Arriendo'), ('ServiciosPublicos', 'Servicios públicos'), ('Proveedores', 'Pago a proveedores'), ('Nomina', 'Nómina / Salarios'), ('Mantenimiento', 'Mantenimiento'), ('Otros', 'Otros')], default='Otros', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia bancaria'), ('TarjetaDebito', 'Tarjeta débito'), ('TarjetaCredito', 'Tarjeta crédito'), ('Cheque', 'Cheque'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata')], default='Efectivo', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='caja_comprobantes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caja',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_factura_proveedor', models.CharField(max_length=50, unique=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('TarjetaDebito', 'Tarjeta débito'), ('TarjetaCredito', 'Tarjeta crédito'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata')], max_length=20, null=True)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=10)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='facturas_proveedores/')),
            ],
            options={
                'db_table': 'compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('AUTO', 'Marca de Vehículo'), ('REPUESTO', 'Marca de Repuesto/Aceite')], default='AUTO', max_length=10)),
                ('pais_origen', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas_logos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('requiere_seguimiento', models.BooleanField(default=False, help_text='Si está activo, al crear una orden con este servicio se pedirá la fecha del próximo mantenimiento.')),
                ('requiere_productos', models.BooleanField(default=False, help_text='Si está activo, la orden no podrá guardarse sin al menos un producto agregado.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'db_table': 'tipo_servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=3)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(choices=[('ADMIN', 'Administrador'), ('MECANICO', 'Mecánico')], default='ADMIN', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/')),
                ('debe_cambiar_password', models.BooleanField(default=False, help_text='Si está activo, el usuario deberá cambiar su contraseña al iniciar sesión.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'db_table': 'usuario_sistema',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('km_actual', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'cargo': 'MECANICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mecánico responsable')),
            ],
            options={
                'db_table': 'orden_servicio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('unidad_medida', models.CharField(choices=[('UND', 'Unidad'), ('LT', 'Litro'), ('ML', 'Mililitro'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('MT', 'Metro'), ('CM', 'Centímetro'), ('GL', 'Galón'), ('PAR', 'Par'), ('KIT', 'Kit'), ('CJA', 'Caja'), ('RLL', 'Rollo'), ('JGO', 'Juego')], default='UND', max_length=5, verbose_name='Unidad de medida')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('estado', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(limit_choices_to={'categoria': 'REPUESTO', 'estado': True}, on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SERVICIO', 'Orden de Servicio'), ('PRODUCTO', 'Venta de Producto'), ('COMPRA', 'Compra a Proveedor')], default='SERVICIO', max_length=10)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='facturas_comprobantes/')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', max_length=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('TarjetaDebito', 'Tarjeta Débito'), ('Nequi', 'Nequi'), ('Daviplata', 'Daviplata')], max_length=20, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.compra')),
                ('orden_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ordenservicio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto')),
            ],
            options={
                'db_table': 'factura',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Precio del producto en el momento de agregarlo a la orden', max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_usados', to='app.ordenservicio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
            ],
            options={
                'db_table': 'detalle_orden_producto',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
        migrations.CreateModel(
            name='OrdenServicioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_detalle', to='app.ordenservicio')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tiposervicio')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio en Orden',
                'db_table': 'orden_servicio_detalle',
                'unique_together': {('orden', 'tipo_servicio')},
            },
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='servicios',
            field=models.ManyToManyField(through='app.OrdenServicioDetalle', to='app.tiposervicio', verbose_name='Servicios'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('tipo_uso', models.CharField(choices=[('BAJO', 'Uso bajo (ciudad, poco uso)'), ('NORMAL', 'Uso normal (estándar)'), ('ALTO', 'Uso alto (viajes frecuentes)'), ('CARGA', 'Carga / Transporte (intensivo)')], default='NORMAL', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('marca', models.ForeignKey(limit_choices_to={'categoria': 'AUTO', 'estado': True}, on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
            options={
                'db_table': 'vehiculo',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_al_momento', models.IntegerField(help_text='Km del vehículo cuando se registró este seguimiento')),
                ('km_proximo_mantenimiento', models.IntegerField(blank=True, help_text='A qué km debe volver (opcional)', null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, help_text='Cuándo debe volver', null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=15)),
                ('activo', models.BooleanField(default=True, help_text='Solo el seguimiento activo más reciente importa para alertas')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('orden_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='app.ordenservicio')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tiposervicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='app.vehiculo')),
            ],
            options={
                'verbose_name': 'Seguimiento de Mantenimiento',
                'verbose_name_plural': 'Seguimientos de Mantenimiento',
                'db_table': 'seguimiento_mantenimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehiculo'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Alerta', 'Alerta'), ('Recordatorio', 'Recordatorio'), ('Mantenimiento', 'Mantenimiento'), ('Urgente', 'Urgente'), ('Informacion', 'Información')], max_length=50)),
                ('origen', models.CharField(choices=[('SISTEMA', 'Automática del sistema'), ('ADMIN', 'Creada por administrador')], default='ADMIN', max_length=10)),
                ('titulo', models.CharField(blank=True, max_length=150)),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la notificación (hoy o en el futuro).', validators=[app.models.validar_fecha_presente_o_futura])),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehiculo')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'db_table': 'compra_detalle',
                'unique_together': {('compra', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_proveedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='app.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='app.proveedor')),
            ],
            options={
                'verbose_name': 'Producto del Proveedor',
                'db_table': 'proveedor_producto',
                'unique_together': {('proveedor', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='CompatibilidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_vehiculo', models.ForeignKey(limit_choices_to={'categoria': 'AUTO', 'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('producto', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tiposervicio')),
            ],
            options={
                'db_table': 'compatibilidad_producto',
                'unique_together': {('producto', 'marca_vehiculo', 'tipo_servicio')},
            },
        ),
    ]
